# -*- coding: utf-8 -*-
"""Analyzing Impact of Castle Doctrine on Crime Rates.ipynb
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1vBYVKty7cbbVmTp2-FsD6Jl3igM4l0fa

---

## **Analyzing the Impact of Castle Doctrine Laws on Violent Crime Rates**

### Introduction

The **Castle Doctrine** is a legal principle that grants individuals the right to use reasonable force, including deadly force, to defend themselves against an intruder within their own homes. Rooted in the notion that one's home is their "castle," these laws eliminate the duty to retreat before using force in self-defense. Proponents argue that the Castle Doctrine empowers lawful homeowners to protect themselves and deters criminal activity, while critics express concerns that such laws may escalate violence and lead to an increase in homicides.

Understanding the **causal relationship** between the implementation of Castle Doctrine laws and changes in violent crime rates is crucial for policymakers, law enforcement agencies, and communities. By analyzing this relationship, I can assess whether these laws effectively reduce crime or inadvertently contribute to higher rates of violence.

### Dataset Overview

This analysis utilizes a comprehensive dataset from the **FBI**, encompassing various states over multiple years. The dataset captures a wide range of variables related to violent crimes, socioeconomic conditions, and demographic factors. Notably, the implementation of Castle Doctrine laws occurred at different times across states, with the majority adopting these statutes around **2006**. This staggered adoption provides a unique opportunity to employ robust methodologies to isolate the effect of these laws on violent crime rates.

### Selected Columns for Analysis

For a focused and meaningful analysis, I restrict our examination to the following columns from the dataset:

| **Column**         | **Description**                                                                                                                                                                                                                 |
|--------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `year`             | The calendar year of the observation (e.g., 2005, 2010).                                                                                                                                                                       |
| `post`             | A binary indicator where `1` signifies the post-treatment period (after the implementation of Castle Doctrine laws) and `0` denotes the pre-treatment period.                                                                    |
| `sid`              | The state identifier, uniquely representing each state in the dataset.                                                                                                                                                       |
| `homicide`         | The number of homicides recorded in the state per 100,000 population for the given year.                                                                                                                                       |
| `robbery`          | The number of robberies reported in the state per 100,000 population for the given year.                                                                                                                                        |
| `larceny`          | The number of larcenies recorded in the state per 100,000 population for the given year.                                                                                                                                        |
| `assault`          | The number of aggravated assaults reported in the state per 100,000 population for the given year.                                                                                                                              |
| `burglary`         | The number of burglaries recorded in the state per 100,000 population for the given year.
| `l_exp_pubwelfare`         | Logged public welfare spending                                                                                                                                        |
| `l_police`         | Logged police presence                                                                                                                                        |
| `l_income`         | Logged income                                                                                                                                        |
| `murder`           | The number of murders reported in the state per 100,000 population for the given year.                                                                                                                                          |
| `unemployrt`       | The unemployment rate in the state for the given year, serving as an economic indicator.                                                                                                                                          |
| `poverty`          | The poverty rate in the state for the given year, reflecting socioeconomic conditions.                                                                                                                                           |
| `blackm_15_24`     | The percentage of Black males aged 15-24 in the state for the given year.                                                                                                                                                        |
| `whitem_15_24`     | The percentage of White males aged 15-24 in the state for the given year.                                                                                                                                                        |
| `popwt`     | Population weight                                                                                                                                                                                                                       |

### **Crime Definitions**

To ensure clarity in our analysis, it's essential to define each of the key crime-related variables included in our dataset:

| **Variable**   | **Definition**                                                                                                                                                                                                                     |
|----------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Homicide**   | **Homicide** is defined as the sum of **murder** and **non-negligent manslaughter**. It represents the total number of intentional killings within a state, normalized per 100,000 state population.                                 |
| **Murder**     | **Murder** refers to the unlawful killing of another human being without justification or valid excuse, committed with the necessary intention as defined by the law in a specific jurisdiction.                                           |
| **Larceny**    | **Larceny** is the unlawful taking and carrying away of personal property with the intent to deprive the rightful owner of it permanently. It encompasses various forms of theft that do not involve force or intimidation.               |
| **Assault**    | **Assault** involves the act of causing physical harm or unwanted physical contact to another person. This includes aggravated assaults, which are more severe and may involve the use of weapons or intent to cause serious injury.       |
| **Burglary**   | **Burglary** is the act of illegally entering a building or other areas without permission, typically with the intention of committing a further criminal offense inside. It does not necessarily involve theft or violence.            |
| **Robbery**    | **Robbery** is the act of taking property or money from a person through force, intimidation, or threat of violence. Unlike larceny, robbery involves direct confrontation and coercion against the victim.                                |


### **Temporal and Spatial Dimensions**

The dataset spans multiple states across the United States and covers several years, allowing for a longitudinal analysis of crime trends in relation to the implementation of Castle Doctrine laws. Most states adopted these statutes around **2006**, but the exact year of implementation varies, providing a natural experiment setting to evaluate the laws' impact. By comparing states before and after the adoption period and against states that did not adopt the law during the study period, we can effectively employ different techniques to infer causality.

---
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
!pip install dowhy
import dowhy
from sklearn.linear_model import LinearRegression

"""Load `castle_doctrine_1.csv` into `df_1` and `castle_doctrine_2.csv` into `df_2`. Display the first 5 rows of `df_1` and last 5 rows of `df_2`."""

# Load csv files
df_1 = pd.read_csv("castle_doctrine_1.csv")
df_2 = pd.read_csv("castle_doctrine_2.csv")

# Display the first 5 rows of df_1
print("first 5 rows of df_1:")
print(df_1.head())

# Display the last 5 rows of df_2
print("\nfirst 5 rows of df_2:")
print(df_2.tail())

"""Store the total number of null values in both datasets in `nullTotal`."""

null_count_df1 = df_1.isnull().sum().sum()
null_count_df2 = df_2.isnull().sum().sum()

nullTotal = null_count_df1 + null_count_df2

print(nullTotal)

"""Store the number of rows containing null values in both datasets in `rowsNull`."""

rows_null_df1 = df_1.isnull().any(axis=1).sum()
rows_null_df2 = df_2.isnull().any(axis=1).sum()

rowsNull = rows_null_df1 + rows_null_df2

print(rowsNull)

"""Drop all rows containing null values, and print the sizes of the resulting datasets."""

# Drop all rows containing null values
df_1.dropna(inplace=True)
df_2.dropna(inplace=True)

# Print the sizes of the resulting datasets
print("Size of df_1 after dropping nulls (rows, columns):", df_1.shape)
print("Size of df_2 after dropping nulls (rows, columns):", df_2.shape)

"""Note that the id column in `df_1` is shuffled and not in order. Sort all the rows in the dataframe in ascending order using the `id` column."""

# Sort df_1 by the 'id' column in ascending order
df_1.sort_values(by='id', ascending=True, inplace=True)

"""The dataset is split across two files; both files share an `id` column with identical row counts and therefore, a one-to-one mapping — join them on `id` and store the merged table in a variable named `df`."""

# Perform an inner merge on the 'id' column
df = pd.merge(df_1, df_2, on='id', how='inner')

# To confirm
print("Shape of the merged DataFrame:", df.shape)
print("\nFirst 5 rows of df:")
print(df.head())

"""We do not need the `id` column any longer. Drop the `id` column."""

# Drop the 'id' column from df because it not useful for statistical analysis
df.drop('id', axis=1, inplace=True)

"""Plot a correlation heatmap for this dataset using the `selected_columns` (it will be a color coded graph indicating correlation values for each of the columns against every other column)."""

selected_columns = ['post', 'homicide', 'robbery', 'larceny',
                    'assault', 'burglary', 'murder', 'unemployrt','l_exp_pubwelfare' ,'l_police','l_income',
                    'poverty', 'blackm_15_24', 'whitem_15_24']

# Plot the Correlation Heatmap
df_corr = df[selected_columns]
correlation_matrix = df_corr.corr()

plt.figure(figsize=(12, 10))
sns.heatmap(
    correlation_matrix,
    annot=False,
    cmap='coolwarm',
    fmt=".2f",
    linewidths=.5,
    cbar_kws={'label': 'Correlation Coefficient'}
)

"""Using 3 notable correlations. Based on these correlations, I will suggest that are causally related? If so, is their causal relationship direct or indirect, and are there any cofounding variables I suspect? Otherwise, i will explain  why I weren't able to deduce any causal relaion.

<span style="color:lightgreen"> Answer: </span>
Based on the calculated correlation matrix:
| Variables              | Correlation (r)  | Type              |
|------------------------|------------------|-------------------|
| l_income vs. Poverty   | -0.840           | Strong Negative   |
| Homicide vs. Poverty   | 0.512            | Moderate Positive |
| Robbery vs. l_police   | 0.545            | Moderate Positive |


**1. l_income and Poverty (r≈−0.84)**
This is the strongest correlation observed. It is a highly expected negative association, as poverty is fundamentally defined by a lack of income. Lower log income logically corresponds to a higher poverty rate.

- **Causality:**
This relationship is likely direct and definitional. A change in income directly changes a person's poverty status.

- **Confounding Variables**: The actual impact of "poverty" can be confounded by differences in Cost of Living across states. Two states with the same average income and poverty rate might have different economic realities based on regional price parity.

**2. Homicide and Poverty (r≈0.51)**
A moderate positive correlation suggesting that states with higher poverty rates tend to experience higher rates of homicide. This aligns with socioeconomic theories of crime.

**Causality:** The correlation does not imply direct causality. Poverty acts as an indirect cause of systemic issues.

**Confounding Variables:**  
The suspected confounding variables are numerous, including:

- **Education and Job Opportunity:**  
  Poverty limits access to quality education and legal employment, creating an environment where violent crime may become more likely.

- **Income Inequality (Gini Coefficient):**  
  The inequal distribution of wealth strongly predicts social unrest and violent crime.

- **Access to Social Services:**  
  States with high poverty often not have access to mental health programs, and community support.


**3. Robbery and l_police (r≈0.54)**
A moderate positive correlation indicates that states with higher robbery rates have a higher logged police presence. This relationship appears counter-intuitive if one assumes police presence is solely a deterrent.

**Causality:** This correlation strongly suggests Reverse Causality or Endogeneity. It is highly probable that a state's high existing crime rate is what causes the state legislature to allocate more resources, thus increasing the police presence. The variable l_police is an effect of high crime, not the cause of it.

**Confounding Variables:** Population Density is a major suspected confounder. Densely populated urban areas naturally have both higher rates of street crime (robbery) and higher per-capita police presence. The density variable drives both the crime rate and the police presence.

I weren't able to deduce any causal relaion because Correlation $\ne$ Causation.

In general, it is impossible to deduce a causal relationship from a simple correlation matrix alone. This is because correlation only measures the strength and direction of a linear association between two variables, but provides no information on following:

- Directionality: We cannot tell if variable A causes B, or B causes A.

- Confounding Variables: The correlation between A and B may be entirely due to a third, unobserved variable C that affects both A and B.

- Spurious Relationships: The correlation may be coincidental.

To establish causality, I would need to employ Difference-in-Differences (DiD) estimation or Instrumental Variables (IV), which are specifically designed to isolate the impact of a treatment while controlling for confounders.

Estimate the average treatment effect on Homicide before and after the doctrine was implemented using the post attribute in my dataset, without conditioning on any variable. I will Store my answer in the `ATE` variable.
"""

# Calculate Average Treatment Effect (ATE)

# Calculate the mean homicide rate for the post-treatment period (post=1)
homicide_mean_post = df[df['post'] == 1]['homicide'].mean()

# Calculate the mean homicide rate for the pre-treatment period (post=0)
homicide_mean_pre = df[df['post'] == 0]['homicide'].mean()

ATE = homicide_mean_post - homicide_mean_pre
print(f"The Average Treatment Effect (ATE) is: {ATE:.4f}")

"""What might the issue with the calculated ATE?

<span style="color:lightgreen"> Answer: </span>

The calculated Average Treatment Effect ($\text{ATE} = 1.3488$) is a highly biased and unreliable estimate of the Castle Doctrine's impact.

The main issue is that the simple $\text{ATE}$ is entirely confounded by  
- secular time trends in crime
- general differences across states.

 **The Confounding variable Issue:**

ATE calculation simply compares the average homicide rate across all states in the years after the law was implemented to the average rate in the years before. If there was pre-existing trend for homicide rates to increase (or decrease) during that time, the calculated $\text{ATE}$ will capture this general trend, not the specific effect of the Castle Doctrine laws. Thus true effect of the law is masked.

Create a plot that shows the number of observations in the pre-treatment and post-treatment periods.
"""

# Plot number of observations in the pre-treatment and post-treatment periods

# Calculate the number of observations in pre and post periods
post_counts = df['post'].value_counts().sort_index()

# Set up the plot
plt.figure(figsize=(7, 5))
sns.barplot(x=post_counts.index, y=post_counts.values, hue=post_counts.index, palette='viridis', dodge=False, legend=False)

# Add labels and title
plt.title('Number of Observations by Treatment Period', fontsize=14)
plt.xlabel('Treatment Period (post)', fontsize=12)
plt.ylabel('Number of Observations (State-Years)', fontsize=12)

# Set x-tick labels
plt.xticks([0, 1], ['Pre-Treatment (Post=0)', 'Post-Treatment (Post=1)'])

# Add count labels on top of the bars
for i, count in enumerate(post_counts.values):
    plt.text(i, count, f'{count}', ha='center', va='bottom', fontsize=10)

plt.tight_layout()

# To Save the figure
plt.savefig('observation_counts_bar_chart.png')
print("Observation_counts_bar_chart.png saved.")

"""For the states that implemented the doctrine, use an appropriate plot to visualise the number of observations for the 5 states with the highest number of overall samples (pre and post). In the plot, separate counts for pre and post-treatment periods."""

# Plot Top 5 Treated States

# Identify states that implemented the doctrine (where max(post) == 1)
treated_sids = df.groupby('sid')['post'].max()
treated_sids = treated_sids[treated_sids == 1].index.tolist()

# Filter the dataframe to only include treated states
df_treated = df[df['sid'].isin(treated_sids)]

# Find the 5 states with the highest total number of overall samples
top_5_sids = df_treated.groupby('sid').size().nlargest(5).index.tolist()

# Filter for the top 5 states and aggregate by sid and post period
df_top_5 = df_treated[df_treated['sid'].isin(top_5_sids)]
plot_data = df_top_5.groupby(['sid', 'post']).size().reset_index(name='count')

# Map 'post' to meaningful labels
plot_data['period'] = plot_data['post'].map({0: 'Pre-Treatment', 1: 'Post-Treatment'})

# Create the grouped bar chart
plt.figure(figsize=(10, 6))
bars = sns.barplot(
    x='sid',
    y='count',
    hue='period',
    data=plot_data,
    palette={'Pre-Treatment': 'skyblue', 'Post-Treatment': 'salmon'}
)

# Add counts on top of the bars
for container in bars.containers:
    bars.bar_label(container, fmt='%d', label_type='edge', padding=3)

# Set labels and title
plt.title('Sample Counts (Pre and Post) for Top 5 Castle Doctrine Implementing States', fontsize=14)
plt.xlabel('State Identifier (sid)', fontsize=12)
plt.ylabel('Number of Observations (State-Year)', fontsize=12)
plt.legend(title='Treatment Period')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()

# Save the figure
plt.savefig('top_5_treated_states_samples.png')
print("Top_5_treated_states_samples.png saved.")

"""Since our dataset comprises of data from many states, I want to calculate the per state ATE. Before I do that, I am interested in the ATE of the states with more data samples. Therefore, calculate the per state ATE of the 5 states. I will visualise above and display the results in a dataframe."""

# alculate Per-State ATE for Top 5 Treated States

# Identify states that implemented the doctrine (where post=1 exists)
treated_sids = df.groupby('sid')['post'].max()
treated_sids = treated_sids[treated_sids == 1].index

# Filter the DataFrame to include only treated states
df_treated = df[df['sid'].isin(treated_sids)].copy()

# Find the 5 states with the highest total number of samples
total_samples = df_treated.groupby('sid').size()
top_5_sids = total_samples.nlargest(5).index.tolist()

# Filter the data for only the top 5 states
df_top_5 = df_treated[df_treated['sid'].isin(top_5_sids)]

# Calculate the mean homicide rate for pre (post=0) and post (post=1) periods
homicide_means = df_top_5.groupby(['sid', 'post'])['homicide'].mean().unstack()

# Calculate the Per-State ATE (Post - Pre)
ATE_series = homicide_means[1] - homicide_means[0]
ATE_df = ATE_series.rename('Per_State_ATE').reset_index()

print("Per-State ATE for Homicide in the Top 5 Treated States:\n")
print(ATE_df.to_markdown(index=False, numalign="left", stralign="left"))

"""Compute the overall CATE as follows:
- Select states that were treated in 2010.
- For each selected state, compute the state-level ATE on homicide:

Using the state-level ATEs, compute the CATE and report it.
"""

# Compute Conditional Average Treatment Effect (CATE) for 2010 Treated States

# Identify the first year of treatment (post=1) for each state
min_treatment_year = df[df['post']==1].groupby('sid')['year'].min()

# Select states that were treated in 2010
treated_2010_sids = min_treatment_year[min_treatment_year == 2010].index.tolist()

# Filter the main DataFrame to include only these states
df_2010_treated = df[df['sid'].isin(treated_2010_sids)]

# Group by state (sid) and period (post) and calculate the mean homicide rate
mean_homicide_per_period = df_2010_treated.groupby(['sid', 'post'])['homicide'].mean().unstack()

# Calculate the state-level ATE: Mean(post=1) - Mean(post=0)
state_level_ATEs = mean_homicide_per_period[1] - mean_homicide_per_period[0]

# Compute the CATE
CATE = state_level_ATEs.mean()

# Report the results
print(f"States treated in 2010 (sid): {treated_2010_sids}")
print("\nState-Level ATEs for Homicide (2010 Treated States):")
print(state_level_ATEs.to_frame(name='State_ATE').to_markdown(numalign="left", stralign="left"))
print("\n---")
print(f"The Conditional Average Treatment Effect (CATE) for 2010 treated states is: {CATE:.4f}")

"""Do you observe any evidence for the Simpson's Paradox for any individual state? If so, why do you think this might be the case? I will explain it.

<span style="color:lightgreen"> Answer: </span>

Yes, there is strong evidence for Simpson's Paradox when comparing the overall, unconditioned Average Treatment Effect ($\text{ATE}$) to the individual state-level ATEs.

**Evidence of Simpson's Paradox:**

- The overall ATE calculated in Q7.1 was positive ($\mathbf{+1.3488}$), suggesting that $\text{homicide}$ rates generally increased across the entire dataset after the doctrine period began.

 - When looking at the state-level ATEs for the top $5$ treated states (Q9.2), the majority (4 out of 5) showed a negative ATE, suggesting that $\text{homicide}$ rates decreased within those specific states after implementing the doctrine.

 The overall trend is the reverse of the trend observed in the majority of the individual groups, which is the definition of Simpson's Paradox.

Now, report the ATE on Homicide using the DiD (Difference in Difference) formula where:

-   Assume the pre-intervention period is 2005, while the post-intervention period is 2010,
-   Given S defines your set of all states, your treatment group T consists of the states that have implemented the doctrine in 2010, and your control group are the states S\T in 2005 (i.e. the states apart from those incorporated in T)
"""

# Difference-in-Differences (DiD)

# Identify States treated in 2010, and Find the minimum year where post=1 for each state
treatment_years = df[df['post'] == 1].groupby('sid')['year'].min()

# Select the states that were treated in 2010
Treated_SIDs = treatment_years[treatment_years == 2010].index.tolist()

if not Treated_SIDs:   # To handle empty set, though we expect sid=27
    print("No states were treated in the year 2010. Cannot perform DiD calculation based on this criteria.")
    raise ValueError("Treated group is empty.")

# Identify Control States (C): All other states (S\T)
All_SIDs = df['sid'].unique()
Control_SIDs = [sid for sid in All_SIDs if sid not in Treated_SIDs]

# Filter data for relevant years
df_did = df[df['year'].isin([2005, 2010])]

# Calculate the Four Means for DiD
homicide_means = df_did.groupby(['sid', 'year'])['homicide'].mean().reset_index()

# Filter means for Treated Group (T) and Control Group (C)
homicide_T = homicide_means[homicide_means['sid'].isin(Treated_SIDs)]
homicide_C = homicide_means[homicide_means['sid'].isin(Control_SIDs)]

# Calculate the four specific means
Y_T_post = homicide_T[homicide_T['year'] == 2010]['homicide'].mean()
Y_T_pre = homicide_T[homicide_T['year'] == 2005]['homicide'].mean()
Y_C_post = homicide_C[homicide_C['year'] == 2010]['homicide'].mean()
Y_C_pre = homicide_C[homicide_C['year'] == 2005]['homicide'].mean()

# Calculate DiD Estimator
DiD = (Y_T_post - Y_T_pre) - (Y_C_post - Y_C_pre)

# Report the results
print(f"Treated State ID (T): {Treated_SIDs}")
print(f"Mean Homicide Rate (Treated, Post=2010): {Y_T_post:.4f}")
print(f"Mean Homicide Rate (Treated, Pre=2005): {Y_T_pre:.4f}\n")
print(f"Mean Homicide Rate (Control, Post=2010): {Y_C_post:.4f}")
print(f"Mean Homicide Rate (Control, Pre=2005): {Y_C_pre:.4f}")
print("-" * 45)
print(f"Treated Group Change (Post - Pre): {(Y_T_post - Y_T_pre):.4f}")
print(f"Control Group Change (Post - Pre): {(Y_C_post - Y_C_pre):.4f}")
print("-" * 45)
print(f"Difference-in-Differences (DiD) Estimate: {DiD:.4f}")

"""Plot the overall average homicides per year in appropriate graph."""

# Plot Overall Average Homicides per Year

# Calculate the overall average homicide rate grouped by year
homicide_by_year = df.groupby('year')['homicide'].mean().reset_index()

# Create the line plot
plt.figure(figsize=(10, 6))
sns.lineplot(
    data=homicide_by_year,
    x='year',
    y='homicide',
    marker='o',
    color='b',
    linewidth=2
)

# Add context (The majority of states adopted the law around 2006)
plt.axvline(x=2006, color='r', linestyle='--', label='Approx. Adoption Year(2006) as mention in introduction')

# Set labels and title
plt.title('Overall Average Homicide Rate per Year', fontsize=16)
plt.xlabel('Year', fontsize=12)
plt.ylabel('Average Homicide Rate (per 100,000)', fontsize=12)
plt.legend()
plt.xticks(homicide_by_year['year']) # Ensure all years are marked on the x-axis
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()

# To save the figure
plt.savefig('overall_homicide_trend.png')
print("overall_homicide_trend.png saved.")

"""Synthesize the results from your analyses (correlation heatmap, raw ATE, per‑state ATEs, CATE, DiD, plots). Based on this evidence, state whether you believe the Castle Doctrine had a causal effect, positive or negative, on homicide rates and justify your conclusion with specific findings. Then list the main limitations and identification threats in your approach.

Cite specific results (numbers or trends) that support or contradict a causal effect.
Identify likely confounders and how they could bias estimates.
Note methodological limitations (e.g., aggregated vs. within‑state effects, parallel trends assumption for DiD).
I will explain it.

<span style="color:lightgreen"> Answer: </span>

Based on the synthesis of the calculated metrics and visualizations, I conclude, there is insufficient evidence that the Castle Doctrine had a causal effect, either positive or negative, on homicide rates.

**1. Evidence of a Positive Causal Effect**

- The Difference-in-Differences (DiD) estimate shows an increase of about +1.41 homicides per 100,000 in the treated state compared to the trend in control states.
- This is considered the most reliable estimate and suggests the law may have increased homicide rates.

**2. Evidence Suggesting a Negative Effect or No Effect**

- The raw ATE shows an increase of +1.35 homicides, but this is misleading because it does not account for trends in the control group.

- Many state-level ATEs show a decrease in homicides after the law was adopted, indicating that effects vary across states.

- The CATE for a specific treated state in 2010 shows a decrease of -0.30, which contradicts the DiD estimate.
Overall trends in the data show a drop in homicide rates after 2007, suggesting the positive raw ATE might be caused by timing or selection bias, not the law itself.

**Methodological Limitations:**

The DiD estimate is based on only one treated state, so it is very sensitive to state-specific events or errors.

The parallel trends assumption may be violated:
- The control group had a strong downward trend before treatment.
- The treated state had a slight upward trend before treatment.
- This can bias the DiD estimate.

There is a large data imbalance:
- Many more pre-treatment observations than post-treatment ones.
- This makes post-treatment averages and ATE calculations unstable or misleading.

**Identification Threats:(Confounders)**

Socioeconomic factors (like poverty and unemployment) are strongly related to homicide rates and the post-treatment period, causing omitted variable bias.

Reverse causality may occur:
- States with rising crime may be more likely to adopt the Castle Doctrine, making the effect appear larger than it really is.

Unobserved factors can affect both crime rates and law adoption:
- Gun ownership rates
- Drug enforcement policies
- Cultural attitudes toward violence

These factors confound the estimates, making causal conclusions less reliable.

**Final Conclusion**

Although the DiD estimate suggests the Castle Doctrine might have increased homicide rates, this conclusion is uncertain. The parallel trends assumption seems violated, many states show negative ATEs, and overall homicide trends are declining, so the result is not reliable.

A more robust analysis would require an advanced event-study or generalized DiD model that incorporates all states, multiple years, and key time-varying covariates such as unemployment and poverty rates. Only with such a comprehensive approach could we confidently assess the causal impact of the law.
"""